export const TOAST_MESSAGE_ERROR_CODES = {
  CR_NUMBER: 'CrNumber',
  ENTITY_404: 'ENTITY-404',
  ENTITY_301: 'ENTITY-301',
  VEHICLE_IDENTIFIER: 'VehicleIdentifier',
  MANUFACTURE_YEAR: 'ManufactureYear',
  NETWORK_ERROR: 'ERR_NETWORK',
  VEHICLE_409_DUPLICATE: 'VEHICLE-409-DUPLICATE',
  VEHICLE_409_MAX: 'VEHICLE-409-MAX',
} as const

export const EXCEL_UPLOAD_ERROR_CODES = {
  FILE_400: 'FILE-400',
  TABLE_400: 'TABLE-400',
  COLUMN_400: 'COLUMN-400',
  ROW_400: 'ROW-400',
  LINE_400: 'LINE-400',
  VEHICLES: 'Vehicles',
} as const

export const VEHICLE_ERROR_CODES = {
  VEHICLE_404: 'VEHICLE-404',
  VEHICLE_409_YEAR: 'VEHICLE-409-YEAR',
  VEHICLE_409_MAKE: 'VEHICLE-409-MAKE',
  VEHICLE_409_MODEL: 'VEHICLE-409-MODEL',
  VEHICLE_409_BODY: 'VEHICLE-409-BODY',
  VEHICLE_409_SEQUENCE: 'VEHICLE-409-SEQUENCE',
} as const

export const VALIDATE_OTP_ERROR_CODES = {
  OTP_INVALID: 'OTP-INVALID',
  OTP_MAX: 'OTP-MAX',
  OTP_EXPIRED: 'OTP-EXPIRED',
  OTP_BLOCKED: 'OTP-BLOCKED',
} as const

export const QUOTES_ERROR_CODES = {
  ACTIVE_QUOTE_LIST_EXISTS: 'QUOTE-409-EXIST',
} as const

export const ERROR_CODES = {
  ...TOAST_MESSAGE_ERROR_CODES,
  ...EXCEL_UPLOAD_ERROR_CODES,
  ...VEHICLE_ERROR_CODES,
  ...VALIDATE_OTP_ERROR_CODES,
  ...QUOTES_ERROR_CODES,
} as const

export type ToastMessageErrorCodeKey = keyof typeof TOAST_MESSAGE_ERROR_CODES
export type ExcelUploadErrorCodeKey = keyof typeof EXCEL_UPLOAD_ERROR_CODES
export type VehicleErrorCodeKey = keyof typeof VEHICLE_ERROR_CODES
export type ErrorCodeKey = keyof typeof ERROR_CODES
