export const FLEET_LIST_PAGE_SIZE = 10
export const TPL_VEHICLES_PAGE_SIZE = 10
export const COMP_VEHICLES_PAGE_SIZE = 10
export const AVAILABLE_QUOTES_PAGE_SIZE = 10
export const PURCHASED_POLICIES_PAGE_SIZE = 10
